export const Types = {
    //Location
    GET_STREETS: 'GET_STREETS',
    GET_HOUSES: 'GET_HOUSES',
    GET_HOUSES_FLATS: 'GET_HOUSES_FLATS',
    HOUSES_SELECT_DISABLED: 'HOUSES_SELECT_DISABLED',
    HOUSES_FLATS_SELECT_DISABLED: 'HOUSES_FLATS_SELECT_DISABLED'
};